

/*//////////////////////////////////////////////////////////////////////////////////////
////// Autogenerated by JaySvcUtil.exe http://JayData.org for more info        /////////
//////                             oData  V3                                     /////////
//////////////////////////////////////////////////////////////////////////////////////*/
(function(global, $data, undefined) {

    
  $data.Entity.extend('Model_Northwind_EF.Alphabetical_list_of_products', {
     'ProductID': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
     'ProductName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':40 },
     'Discontinued': { 'key':true,'type':'Edm.Boolean','nullable':false,'required':true },
     'CategoryName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':15 },
     'SupplierID': { 'type':'Edm.Int32' },
     'CategoryID': { 'type':'Edm.Int32' },
     'QuantityPerUnit': { 'type':'Edm.String','maxLength':20 },
     'UnitPrice': { 'type':'Edm.Decimal' },
     'UnitsInStock': { 'type':'Edm.Int16' },
     'UnitsOnOrder': { 'type':'Edm.Int16' },
     'ReorderLevel': { 'type':'Edm.Int16' }
  });

  $data.Entity.extend('Model_Northwind_EF.Categories', {
     'CategoryID': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CategoryName': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':15 },
     'Description': { 'type':'Edm.String','maxLength':Number.POSITIVE_INFINITY },
     'Picture': { 'type':'Edm.Binary','maxLength':Number.POSITIVE_INFINITY },
     'Products': { 'type':'Array','elementType':'Model_Northwind_EF.Products','inverseProperty':'Categories' }
  });

  $data.Entity.extend('Model_Northwind_EF.Products', {
     'ProductID': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'ProductName': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':40 },
     'SupplierID': { 'type':'Edm.Int32' },
     'CategoryID': { 'type':'Edm.Int32' },
     'QuantityPerUnit': { 'type':'Edm.String','maxLength':20 },
     'UnitPrice': { 'type':'Edm.Decimal' },
     'UnitsInStock': { 'type':'Edm.Int16' },
     'UnitsOnOrder': { 'type':'Edm.Int16' },
     'ReorderLevel': { 'type':'Edm.Int16' },
     'Discontinued': { 'type':'Edm.Boolean','nullable':false,'required':true },
     'Categories': { 'type':'Model_Northwind_EF.Categories','inverseProperty':'Products' },
     'Order_Details': { 'type':'Array','elementType':'Model_Northwind_EF.Order_Details','inverseProperty':'Products' },
     'Suppliers': { 'type':'Model_Northwind_EF.Suppliers','inverseProperty':'Products' }
  });

  $data.Entity.extend('Model_Northwind_EF.Order_Details', {
     'OrderID': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
     'ProductID': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
     'UnitPrice': { 'type':'Edm.Decimal','nullable':false,'required':true },
     'Quantity': { 'type':'Edm.Int16','nullable':false,'required':true },
     'Discount': { 'type':'Edm.Single','nullable':false,'required':true },
     'Orders': { 'type':'Model_Northwind_EF.Orders','required':true,'inverseProperty':'Order_Details' },
     'Products': { 'type':'Model_Northwind_EF.Products','required':true,'inverseProperty':'Order_Details' }
  });

  $data.Entity.extend('Model_Northwind_EF.Orders', {
     'OrderID': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CustomerID': { 'type':'Edm.String','maxLength':5 },
     'EmployeeID': { 'type':'Edm.Int32' },
     'OrderDate': { 'type':'Edm.DateTime' },
     'RequiredDate': { 'type':'Edm.DateTime' },
     'ShippedDate': { 'type':'Edm.DateTime' },
     'ShipVia': { 'type':'Edm.Int32' },
     'Freight': { 'type':'Edm.Decimal' },
     'ShipName': { 'type':'Edm.String','maxLength':40 },
     'ShipAddress': { 'type':'Edm.String','maxLength':60 },
     'ShipCity': { 'type':'Edm.String','maxLength':15 },
     'ShipRegion': { 'type':'Edm.String','maxLength':15 },
     'ShipPostalCode': { 'type':'Edm.String','maxLength':10 },
     'ShipCountry': { 'type':'Edm.String','maxLength':15 },
     'Customers': { 'type':'Model_Northwind_EF.Customers','inverseProperty':'Orders' },
     'Employees': { 'type':'Model_Northwind_EF.Employees','inverseProperty':'Orders' },
     'Order_Details': { 'type':'Array','elementType':'Model_Northwind_EF.Order_Details','inverseProperty':'Orders' },
     'Shippers': { 'type':'Model_Northwind_EF.Shippers','inverseProperty':'Orders' }
  });

  $data.Entity.extend('Model_Northwind_EF.Customers', {
     'CustomerID': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':5 },
     'CompanyName': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':40 },
     'ContactName': { 'type':'Edm.String','maxLength':30 },
     'ContactTitle': { 'type':'Edm.String','maxLength':30 },
     'Address': { 'type':'Edm.String','maxLength':60 },
     'City': { 'type':'Edm.String','maxLength':15 },
     'Region': { 'type':'Edm.String','maxLength':15 },
     'PostalCode': { 'type':'Edm.String','maxLength':10 },
     'Country': { 'type':'Edm.String','maxLength':15 },
     'Phone': { 'type':'Edm.String','maxLength':24 },
     'Fax': { 'type':'Edm.String','maxLength':24 },
     'CustomerDemographics': { 'type':'Array','elementType':'Model_Northwind_EF.CustomerDemographics','inverseProperty':'Customers' },
     'Orders': { 'type':'Array','elementType':'Model_Northwind_EF.Orders','inverseProperty':'Customers' }
  });

  $data.Entity.extend('Model_Northwind_EF.CustomerDemographics', {
     'CustomerTypeID': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':10 },
     'CustomerDesc': { 'type':'Edm.String','maxLength':Number.POSITIVE_INFINITY },
     'Customers': { 'type':'Array','elementType':'Model_Northwind_EF.Customers','inverseProperty':'CustomerDemographics' }
  });

  $data.Entity.extend('Model_Northwind_EF.Employees', {
     'EmployeeID': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'LastName': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':20 },
     'FirstName': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':10 },
     'Title': { 'type':'Edm.String','maxLength':30 },
     'TitleOfCourtesy': { 'type':'Edm.String','maxLength':25 },
     'BirthDate': { 'type':'Edm.DateTime' },
     'HireDate': { 'type':'Edm.DateTime' },
     'Address': { 'type':'Edm.String','maxLength':60 },
     'City': { 'type':'Edm.String','maxLength':15 },
     'Region': { 'type':'Edm.String','maxLength':15 },
     'PostalCode': { 'type':'Edm.String','maxLength':10 },
     'Country': { 'type':'Edm.String','maxLength':15 },
     'HomePhone': { 'type':'Edm.String','maxLength':24 },
     'Extension': { 'type':'Edm.String','maxLength':4 },
     'Photo': { 'type':'Edm.Binary','maxLength':Number.POSITIVE_INFINITY },
     'Notes': { 'type':'Edm.String','maxLength':Number.POSITIVE_INFINITY },
     'ReportsTo': { 'type':'Edm.Int32' },
     'PhotoPath': { 'type':'Edm.String','maxLength':255 },
     'Employees1': { 'type':'Array','elementType':'Model_Northwind_EF.Employees','inverseProperty':'Employees2' },
     'Employees2': { 'type':'Model_Northwind_EF.Employees','inverseProperty':'Employees1' },
     'Orders': { 'type':'Array','elementType':'Model_Northwind_EF.Orders','inverseProperty':'Employees' },
     'Territories': { 'type':'Array','elementType':'Model_Northwind_EF.Territories','inverseProperty':'Employees' }
  });

  $data.Entity.extend('Model_Northwind_EF.Territories', {
     'TerritoryID': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':20 },
     'TerritoryDescription': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
     'RegionID': { 'type':'Edm.Int32','nullable':false,'required':true },
     'Employees': { 'type':'Array','elementType':'Model_Northwind_EF.Employees','inverseProperty':'Territories' },
     'Region': { 'type':'Model_Northwind_EF.Region','required':true,'inverseProperty':'Territories' }
  });

  $data.Entity.extend('Model_Northwind_EF.Region', {
     'RegionID': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
     'RegionDescription': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
     'Territories': { 'type':'Array','elementType':'Model_Northwind_EF.Territories','inverseProperty':'Region' }
  });

  $data.Entity.extend('Model_Northwind_EF.Shippers', {
     'ShipperID': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CompanyName': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':40 },
     'Phone': { 'type':'Edm.String','maxLength':24 },
     'Orders': { 'type':'Array','elementType':'Model_Northwind_EF.Orders','inverseProperty':'Shippers' }
  });

  $data.Entity.extend('Model_Northwind_EF.Suppliers', {
     'SupplierID': { 'key':true,'type':'Edm.Int32','nullable':false,'computed':true },
     'CompanyName': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':40 },
     'ContactName': { 'type':'Edm.String','maxLength':30 },
     'ContactTitle': { 'type':'Edm.String','maxLength':30 },
     'Address': { 'type':'Edm.String','maxLength':60 },
     'City': { 'type':'Edm.String','maxLength':15 },
     'Region': { 'type':'Edm.String','maxLength':15 },
     'PostalCode': { 'type':'Edm.String','maxLength':10 },
     'Country': { 'type':'Edm.String','maxLength':15 },
     'Phone': { 'type':'Edm.String','maxLength':24 },
     'Fax': { 'type':'Edm.String','maxLength':24 },
     'HomePage': { 'type':'Edm.String','maxLength':Number.POSITIVE_INFINITY },
     'Products': { 'type':'Array','elementType':'Model_Northwind_EF.Products','inverseProperty':'Suppliers' }
  });

  $data.Entity.extend('Model_Northwind_EF.Category_Sales_for_1997', {
     'CategoryName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':15 },
     'CategorySales': { 'type':'Edm.Decimal' }
  });

  $data.Entity.extend('Model_Northwind_EF.Current_Product_List', {
     'ProductID': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
     'ProductName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':40 }
  });

  $data.Entity.extend('Model_Northwind_EF.Customer_and_Suppliers_by_City', {
     'CompanyName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':40 },
     'Relationship': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':9 },
     'City': { 'type':'Edm.String','maxLength':15 },
     'ContactName': { 'type':'Edm.String','maxLength':30 }
  });

  $data.Entity.extend('Model_Northwind_EF.Invoices', {
     'CustomerName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':40 },
     'Salesperson': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':31 },
     'OrderID': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
     'ShipperName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':40 },
     'ProductID': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
     'ProductName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':40 },
     'UnitPrice': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'Quantity': { 'key':true,'type':'Edm.Int16','nullable':false,'required':true },
     'Discount': { 'key':true,'type':'Edm.Single','nullable':false,'required':true },
     'ShipName': { 'type':'Edm.String','maxLength':40 },
     'ShipAddress': { 'type':'Edm.String','maxLength':60 },
     'ShipCity': { 'type':'Edm.String','maxLength':15 },
     'ShipRegion': { 'type':'Edm.String','maxLength':15 },
     'ShipPostalCode': { 'type':'Edm.String','maxLength':10 },
     'ShipCountry': { 'type':'Edm.String','maxLength':15 },
     'CustomerID': { 'type':'Edm.String','maxLength':5 },
     'Address': { 'type':'Edm.String','maxLength':60 },
     'City': { 'type':'Edm.String','maxLength':15 },
     'Region': { 'type':'Edm.String','maxLength':15 },
     'PostalCode': { 'type':'Edm.String','maxLength':10 },
     'Country': { 'type':'Edm.String','maxLength':15 },
     'OrderDate': { 'type':'Edm.DateTime' },
     'RequiredDate': { 'type':'Edm.DateTime' },
     'ShippedDate': { 'type':'Edm.DateTime' },
     'ExtendedPrice': { 'type':'Edm.Decimal' },
     'Freight': { 'type':'Edm.Decimal' }
  });

  $data.Entity.extend('Model_Northwind_EF.Order_Details_Extended', {
     'OrderID': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
     'ProductID': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
     'ProductName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':40 },
     'UnitPrice': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
     'Quantity': { 'key':true,'type':'Edm.Int16','nullable':false,'required':true },
     'Discount': { 'key':true,'type':'Edm.Single','nullable':false,'required':true },
     'ExtendedPrice': { 'type':'Edm.Decimal' }
  });

  $data.Entity.extend('Model_Northwind_EF.Order_Subtotals', {
     'OrderID': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
     'Subtotal': { 'type':'Edm.Decimal' }
  });

  $data.Entity.extend('Model_Northwind_EF.Orders_Qry', {
     'OrderID': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
     'CompanyName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':40 },
     'CustomerID': { 'type':'Edm.String','maxLength':5 },
     'EmployeeID': { 'type':'Edm.Int32' },
     'OrderDate': { 'type':'Edm.DateTime' },
     'RequiredDate': { 'type':'Edm.DateTime' },
     'ShippedDate': { 'type':'Edm.DateTime' },
     'ShipVia': { 'type':'Edm.Int32' },
     'Freight': { 'type':'Edm.Decimal' },
     'ShipName': { 'type':'Edm.String','maxLength':40 },
     'ShipAddress': { 'type':'Edm.String','maxLength':60 },
     'ShipCity': { 'type':'Edm.String','maxLength':15 },
     'ShipRegion': { 'type':'Edm.String','maxLength':15 },
     'ShipPostalCode': { 'type':'Edm.String','maxLength':10 },
     'ShipCountry': { 'type':'Edm.String','maxLength':15 },
     'Address': { 'type':'Edm.String','maxLength':60 },
     'City': { 'type':'Edm.String','maxLength':15 },
     'Region': { 'type':'Edm.String','maxLength':15 },
     'PostalCode': { 'type':'Edm.String','maxLength':10 },
     'Country': { 'type':'Edm.String','maxLength':15 }
  });

  $data.Entity.extend('Model_Northwind_EF.Product_Sales_for_1997', {
     'CategoryName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':15 },
     'ProductName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':40 },
     'ProductSales': { 'type':'Edm.Decimal' }
  });

  $data.Entity.extend('Model_Northwind_EF.Products_Above_Average_Price', {
     'ProductName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':40 },
     'UnitPrice': { 'type':'Edm.Decimal' }
  });

  $data.Entity.extend('Model_Northwind_EF.Products_by_Category', {
     'CategoryName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':15 },
     'ProductName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':40 },
     'Discontinued': { 'key':true,'type':'Edm.Boolean','nullable':false,'required':true },
     'QuantityPerUnit': { 'type':'Edm.String','maxLength':20 },
     'UnitsInStock': { 'type':'Edm.Int16' }
  });

  $data.Entity.extend('Model_Northwind_EF.Sales_by_Category', {
     'CategoryID': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
     'CategoryName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':15 },
     'ProductName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':40 },
     'ProductSales': { 'type':'Edm.Decimal' }
  });

  $data.Entity.extend('Model_Northwind_EF.Sales_Totals_by_Amount', {
     'OrderID': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
     'CompanyName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':40 },
     'SaleAmount': { 'type':'Edm.Decimal' },
     'ShippedDate': { 'type':'Edm.DateTime' }
  });

  $data.Entity.extend('Model_Northwind_EF.Summary_of_Sales_by_Quarter', {
     'OrderID': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
     'ShippedDate': { 'type':'Edm.DateTime' },
     'Subtotal': { 'type':'Edm.Decimal' }
  });

  $data.Entity.extend('Model_Northwind_EF.Summary_of_Sales_by_Year', {
     'OrderID': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
     'ShippedDate': { 'type':'Edm.DateTime' },
     'Subtotal': { 'type':'Edm.Decimal' }
  });

  $data.EntityContext.extend('Model_Northwind_EF.Northwind', {
     'Alphabetical_list_of_products': { type: $data.EntitySet, elementType: Model_Northwind_EF.Alphabetical_list_of_products},
     'Categories': { type: $data.EntitySet, elementType: Model_Northwind_EF.Categories},
     'Products': { type: $data.EntitySet, elementType: Model_Northwind_EF.Products},
     'Order_Details': { type: $data.EntitySet, elementType: Model_Northwind_EF.Order_Details},
     'Orders': { type: $data.EntitySet, elementType: Model_Northwind_EF.Orders},
     'Customers': { type: $data.EntitySet, elementType: Model_Northwind_EF.Customers},
     'CustomerDemographics': { type: $data.EntitySet, elementType: Model_Northwind_EF.CustomerDemographics},
     'Employees': { type: $data.EntitySet, elementType: Model_Northwind_EF.Employees},
     'Territories': { type: $data.EntitySet, elementType: Model_Northwind_EF.Territories},
     'Region': { type: $data.EntitySet, elementType: Model_Northwind_EF.Region},
     'Shippers': { type: $data.EntitySet, elementType: Model_Northwind_EF.Shippers},
     'Suppliers': { type: $data.EntitySet, elementType: Model_Northwind_EF.Suppliers},
     'Category_Sales_for_1997': { type: $data.EntitySet, elementType: Model_Northwind_EF.Category_Sales_for_1997},
     'Current_Product_List': { type: $data.EntitySet, elementType: Model_Northwind_EF.Current_Product_List},
     'Customer_and_Suppliers_by_City': { type: $data.EntitySet, elementType: Model_Northwind_EF.Customer_and_Suppliers_by_City},
     'Invoices': { type: $data.EntitySet, elementType: Model_Northwind_EF.Invoices},
     'Order_Details_Extended': { type: $data.EntitySet, elementType: Model_Northwind_EF.Order_Details_Extended},
     'Order_Subtotals': { type: $data.EntitySet, elementType: Model_Northwind_EF.Order_Subtotals},
     'Orders_Qry': { type: $data.EntitySet, elementType: Model_Northwind_EF.Orders_Qry},
     'Product_Sales_for_1997': { type: $data.EntitySet, elementType: Model_Northwind_EF.Product_Sales_for_1997},
     'Products_Above_Average_Price': { type: $data.EntitySet, elementType: Model_Northwind_EF.Products_Above_Average_Price},
     'Products_by_Category': { type: $data.EntitySet, elementType: Model_Northwind_EF.Products_by_Category},
     'Sales_by_Category': { type: $data.EntitySet, elementType: Model_Northwind_EF.Sales_by_Category},
     'Sales_Totals_by_Amount': { type: $data.EntitySet, elementType: Model_Northwind_EF.Sales_Totals_by_Amount},
     'Summary_of_Sales_by_Quarter': { type: $data.EntitySet, elementType: Model_Northwind_EF.Summary_of_Sales_by_Quarter},
     'Summary_of_Sales_by_Year': { type: $data.EntitySet, elementType: Model_Northwind_EF.Summary_of_Sales_by_Year}
  });

  $data.generatedContexts = $data.generatedContexts || [];
  $data.generatedContexts.push(Model_Northwind_EF.Northwind);
  
      
})(window, $data);
      
    